### ISSUE TITLE
[beta] TypeError: undefined is not a function

### ISSUE THREAD

**Issue by rklomp** [akveo/react-native-ui-kitten#1870]
## 🐛 Bug Report
Getting `[runtime not ready]: TypeError: undefined is not a function` when loading my project after upgrading to 6.0.0 beta. 

```
08-15 16:09:47.830  7545  7604 E ReactNativeJS: [runtime not ready]: TypeError: undefined is not a function
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: ReactHost{0}.handleHostException(message = "[runtime not ready]: TypeError: undefined is not a function, stack:
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: anonymous@357908:62
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: loadModuleImplementation@254:40
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: guardedLoadModule@166:37
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: metroRequire@79:91
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: anonymous@357615:47
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: loadModuleImplementation@254:40
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: guardedLoadModule@166:37
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: metroRequire@79:91
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: anonymous@335644:37
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: loadModuleImplementation@254:40
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: guardedLoadModule@166:37
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: metroRequire@79:91
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: anonymous@333234:56
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: loadModuleImplementation@254:40
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: guardedLoadModule@166:37
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: metroRequire@79:91
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: anonymous@92922:24
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: loadModuleImplementation@254:40
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: guardedLoadModule@166:37
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: metroRequire@79:91
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: anonymous@3844:20
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: loadModuleImplementation@254:40
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: guardedLoadModule@159:46
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: metroRequire@79:91
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: global@475784:3
08-15 16:09:47.841  7545  7604 W unknown:BridgelessReact: ")
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: Exception in native call from JS
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: com.facebook.react.common.JavascriptException: [runtime not ready]: TypeError: undefined is not a function, stack:
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: anonymous@357908:62
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: loadModuleImplementation@254:40
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: guardedLoadModule@166:37
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: metroRequire@79:91
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: anonymous@357615:47
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: loadModuleImplementation@254:40
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: guardedLoadModule@166:37
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: metroRequire@79:91
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: anonymous@335644:37
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: loadModuleImplementation@254:40
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: guardedLoadModule@166:37
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: metroRequire@79:91
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: anonymous@333234:56
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: loadModuleImplementation@254:40
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: guardedLoadModule@166:37
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: metroRequire@79:91
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: anonymous@92922:24
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: loadModuleImplementation@254:40
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: guardedLoadModule@166:37
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: metroRequire@79:91
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: anonymous@3844:20
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: loadModuleImplementation@254:40
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: guardedLoadModule@159:46
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: metroRequire@79:91
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: global@475784:3
08-15 16:09:47.842  7545  7604 E unknown:ReactNative: 
08-15 16:09:47.842  7545  7604 E unknown:ReactNative:   at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.kt:52)
08-15 16:09:47.842  7545  7604 E unknown:ReactNative:   at com.facebook.react.runtime.ReactInstance$ReactJsExceptionHandlerImpl.reportJsException(ReactInstance.kt:303)
08-15 16:09:47.842  7545  7604 E unknown:ReactNative:   at com.facebook.jni.NativeRunnable.run(Native Method)
08-15 16:09:47.842  7545  7604 E unknown:ReactNative:   at android.os.Handler.handleCallback(Handler.java:942)
08-15 16:09:47.842  7545  7604 E unknown:ReactNative:   at android.os.Handler.dispatchMessage(Handler.java:99)
08-15 16:09:47.842  7545  7604 E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.kt:21)
08-15 16:09:47.842  7545  7604 E unknown:ReactNative:   at android.os.Looper.loopOnce(Looper.java:201)
08-15 16:09:47.842  7545  7604 E unknown:ReactNative:   at android.os.Looper.loop(Looper.java:288)
08-15 16:09:47.842  7545  7604 E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion.startNewBackgroundThread$lambda$0(MessageQueueThreadImpl.kt:152)
08-15 16:09:47.842  7545  7604 E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion.$r8$lambda$YYXYCFexeoKtAeDpeNYkxZZlpbA(Unknown Source:0)
08-15 16:09:47.842  7545  7604 E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
08-15 16:09:47.842  7545  7604 E unknown:ReactNative:   at java.lang.Thread.run(Thread.java:1012)
```

## To Reproduce

Steps I took to upgrade ui-kitten. 
```
npm i @ui-kitten/metro-config@beta @ui-kitten/components@beta @ui-kitten/eva@beta @ui-kitten/eva-icons@beta
npm remove @eva-design/eva
```

Update metro.config.js
```diff
const evaConfig = {
-  evaPackage: '@eva-design/eva',
+  evaPackage: '@ui-kitten/eva',
  customMappingPath: './mapping.json'
}
```

Update import in App.tsx
```diff
- import * as eva from '@eva-design/eva'
+ import * as eva from '@ui-kitten/eva'
```

Applied https://github.com/akveo/react-native-ui-kitten/pull/1869 to get metro bundling succeed.

Start my app:
```
npx expo prebuild --clean
npx expo run:android 
```

## Expected behavior

To work ;)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @ui-kitten/eva  |   6.0.0-beta.1       |
| @ui-kitten/components   |  6.0.0-beta.2       |
| @ui-kitten/eva-icons | 6.0.0-beta.1       |

## Environment information

```bash
  System:
    OS: Windows 11 10.0.26200
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics         
  Binaries:
    Node: 22.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 11.6.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.30.2 - C:\Program Files\nodejs\pnpm.CMD
  SDKs:
    Android SDK:
      API Levels: 29, 33, 33, 34, 35, 36
      Build Tools: 29.0.2, 30.0.3, 33.0.2, 34.0.0, 34.0.0, 35.0.0, 36.0.0
      System Images: android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play Intel x86_64 Atom, android-36 | Google APIs Intel x86_64 Atom
  IDEs:
    Android Studio: AI-221.6008.13.2211.9619390
  npmPackages:
    react: 19.2.3 => 19.2.3 
    react-native: 0.86.2 => 0.86.2 
```
